name        = "ClearMagazine"
license     = "MIT"
licenselink = "https://github.com/iamgini/clearmagazine/blob/main/LICENSE"
description = "A clean, config-driven Hugo theme for blogs, news, and magazines. Forked from Hugoplate; refactored for multi-site use."
homepage    = "https://github.com/iamgini/clearmagazine"
demosite    = ""
min_version = "0.125.0" # set to the minimum Hugo you actually target

tags = [
  "blog",
  "news",
  "magazine",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "tailwindcss"
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies"
]

[author]
name     = "Gineesh Madapparambath"
homepage = "https://iamgini.com"

# Keep attribution to the original project
[original]
author   = "Zeon Studio"
homepage = "https://zeon.studio"
repo     = "https://github.com/zeon-studio/hugoplate"
